### ISSUE TITLE
File type not supported

### ISSUE THREAD

**Issue by nkewden** [SteveSevetS/autocomplete-c-cpp-files#11]
Type: <b>Bug</b>

The autocomplete for my amin.cc C++ file was working but this morning I started getting "file type not supported" when i try Command + Shift + L

Extension version: 1.0.2
VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 6.2.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id b6571eba-8fd2-4113-a921-2d9643887783|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: csel-kh1262-28.cselabs.umn.edu|
|OS|Linux x64 6.2.0-26-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4098)|
|Memory (System)|23.33GB (9.74GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
3ch9d444:30846783
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by SteveSevetS** [comment]
Hi, I just fixed the Bug you were talkink about, i added the support for .cc and .hpp files and now should work just fine, in a couple of minutes it will be available the download of the version 1.0.3, let me know if the problem is solved
